services:
  django-backend-service:
    build:
      context: django-backend/
      dockerfile: Dockerfile
    container_name: django-backend-service
    environment:
      - DEBUG=False
    networks:
      - frontend-network
    ports:
      - 8000:8000
    volumes:
      - "./django-backend/:/django-backend"

  react-fontend-service:
    build:
      context: react-frontend/blogapi
      dockerfile: Dockerfile
    container_name: react-fontend-service
    ports:
      - 3000:3000
    networks:
      - frontend-network

networks:
  frontend-network: